spring.application.name=CitasMedicas
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/citas_medicas_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Desactivar la seguridad autogenerada
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration